// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ATvnqbga7u9Al1HGsYNW4bjix2ELTPc',
    appId: '1:990993367179:web:acfc28e59e23676380548e',
    messagingSenderId: '990993367179',
    projectId: 'serena-327da',
    authDomain: 'serena-327da.firebaseapp.com',
    storageBucket: 'serena-327da.firebasestorage.app',
    measurementId: 'G-LQ65J1LCJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjkFnWT1bL3B-2yVQMvebdVJ9XhTk-ZE8',
    appId: '1:990993367179:android:90ccb383dabc963c80548e',
    messagingSenderId: '990993367179',
    projectId: 'serena-327da',
    storageBucket: 'serena-327da.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4ATvnqbga7u9Al1HGsYNW4bjix2ELTPc',
    appId: '1:990993367179:web:f4f8db130e06830180548e',
    messagingSenderId: '990993367179',
    projectId: 'serena-327da',
    authDomain: 'serena-327da.firebaseapp.com',
    storageBucket: 'serena-327da.firebasestorage.app',
    measurementId: 'G-MBW42GKK0P',
  );
}
